name: Cargo Audit
on:
  pull_request:
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  push:
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  schedule:
  - cron: '0 8 4 * *'
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
